name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display the name of the event that triggered the workflow
        run: |
          echo "Event name ${{ github.event_name }}"
      - name: Display name of the branch that the repository is currently referencing
        run: |
          echo "Branch name ${{ github.ref }}"
          
      - uses: actions/checkout@v3
      
      - name: List all files in the repository
        run: |
          echo "Repo structure"
          tree
      
        
