name: Staged deployments

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Display the name of the event that triggered the workflow
        run: |
          echo "Name of the event ${{ github.event_name }}"
